name: Quire
on: push
permissions:
  actions: read
  checks: read
  contents: write
  deployments: write
  pull-requests: write
  repository-projects: write
  statuses: write
jobs:
  quire-build:
    #runs-on: self-hosted
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
            #- name: Nodejs install
            #  run: |
            #    sudo apt-get update 
            #    sudo apt remove -y nodejs npm
            #    curl -sL https://deb.nodesource.com/setup_19.x | sudo bash -
            #    sudo apt-get -y install nodejs
            #    which node
            #    node -v
            #    which npm
            #    npm --version
            #$- name: Build the website
            #$  run: npx @11ty/eleventy
      - name: Git init
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "gihubaction@users.noreply.github.com"
      - name: Quire install
        run: |
          #sudo npm install --global @11ty/eleventy --unsafe-perm
          #npx @11ty/eleventy
          sudo npm install --global @thegetty/quire-cli
      - name: Quire build
        run: quire build
      - name: GH Pages customizations
        run: |
          rm -rf docs || echo "not removing docs"
          mv _site docs
          touch docs/.nojekyll
          touch docs/_assets/.nojekyll
      - name: Git push back
        run: |
          git add docs
          git commit -m "Quire: publishing assets"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
